# Generated by Django 3.0 on 2019-12-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
