# Generated by Django 3.0 on 2019-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_app', '0002_auto_20191214_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
