# Generated by Django 3.0 on 2019-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_app', '0012_auto_20191225_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
