# Generated by Django 3.0 on 2019-12-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn_app', '0014_auto_20191226_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
