# Generated by Django 3.0 on 2020-01-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_app', '0017_auto_20191229_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
